version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'rvVcNk2p'
    labels:
      - 'npm dependencies'
    commit-message:
      prefix: 'npm prod'
      prefix-development: 'npm dev'
      include: 'scope'

registries:
  dockerhub:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "docker"
    directory: "/docker-registry/dockerhub"
    registries:
      - dockerhub
    schedule:
      interval: "monthly"
    labels:
      - "docker"
    commit-message:
      prefix: "docker"
