name: Github Actions - Workflow for Codecov
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/cache@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    if: github.event.pull_request.state == 'OPEN' && (github.event.pull_request.draft == false) && (github.event.action != 'edited' || github.event.changes.base.ref.from != null)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/cache@v3
        with:
          node-version: 18

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

  format:
    name: Format
    if: github.event.pull_request.state == 'OPEN' && (github.event.pull_request.draft == false) && (github.event.action != 'edited' || github.event.changes.base.ref.from != null)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/cache@v3
        with:
          node-version: 18

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        run: npm install

      - name: Run Lint
        run: npm run format
