name: Docker Image CI

on:
  push:
    branches:
      - 'rvVcNk2p/feature/#25-update-ci-pipeline-for-docker-image-history'
  workflow_run:
    workflows: ["Test and Coverage"]
    types:
      - completed

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/airdrop-farmer:${{ github.sha }}

