name: Test and Coverage

on: 
  - push
  - pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/cache@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Send Dispatch Event
        if: github.ref == 'refs/heads/rvVcNk2p/feature/#25-update-ci-pipeline-for-docker-image-history'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
            --data '{"event_type": "test-and-coverage"}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches


