name: Test and Coverage

on: 
  - push
  - pull_request

jobs:
  run-tests:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 18
        uses: actions/cache@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

