name: Test and Coverage

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/cache@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Print ref name
        run: echo ${{ github.ref }}

      - name: Invoke 'Docker Image CI' without inputs
        if: ${{ github.ref }} == 'refs/heads/master' || ${{ github.ref }} == 'refs/pull/43/merge'
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: docker-image.yml
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

